### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by mrdeadlocked** [TheRandomLabs/RandomConfigs#1]
I can't get a config to run without erroring out minecraft. Would it be possible to include a commented out config that's moving the options.txt?

https://paste.dimdev.org/oveqokefaz.mccrash

{
	"source": "menu.json",
	"destination": "minemenu/menu.json",
	"side": "both",
	"version": 1
}

![image](https://user-images.githubusercontent.com/461352/42186711-a9154334-7e1b-11e8-9d9a-8cfef9b111b1.png)

**Comment by TheRandomLabs** [comment]
I should probably add more clear documentation and error messages, but it has to be an array.
```
[
	{
		"source": "menu.json",
		"destination": "minemenu/menu.json",
		"side": "both",
		"version": 1
	}
]
```

**Comment by mrdeadlocked** [comment]
I got this error after using what you posted. I created the file 'defaultconfigs_old.json' and now my game loaded. Thank you.

Caused by: net.minecraft.util.ReportedException: Failed to read file: C:\technic\technic\modpacks\false-province-new\config\randomconfigs\defaultconfigs_old.json
    at com.therandomlabs.randomconfigs.RandomConfigs.handleException(RandomConfigs.java:152)
    at com.therandomlabs.randomconfigs.RandomConfigs.read(RandomConfigs.java:97)
    at com.therandomlabs.randomconfigs.RandomConfigs.readJson(RandomConfigs.java:114)
    at com.therandomlabs.randomconfigs.DefaultConfigs.handle(DefaultConfigs.java:41)
    at com.therandomlabs.randomconfigs.RandomConfigs.construct(RandomConfigs.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:226)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3927)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.nio.file.NoSuchFileException: C:\technic\technic\modpacks\false-province-new\config\randomconfigs\defaultconfigs_old.json
    at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
    at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
    at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
    at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
    at java.nio.file.Files.newByteChannel(Unknown Source)
    at java.nio.file.Files.newByteChannel(Unknown Source)
    at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
    at java.nio.file.Files.newInputStream(Unknown Source)
    at java.nio.file.Files.newBufferedReader(Unknown Source)
    at java.nio.file.Files.readAllLines(Unknown Source)
    at java.nio.file.Files.readAllLines(Unknown Source)
    at com.therandomlabs.randomconfigs.RandomConfigs.read(RandomConfigs.java:94)

**Comment by TheRandomLabs** [comment]
Oh, I screwed up again. I'll fix that.
